version: "3.8"

services:
  geometa:
    build: .
    container_name: geometa_gallery
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Set any runtime env vars here (DB paths, secrets, etc.)
      - NODE_ENV=production
    volumes:
      # Persist the SQLite database file outside the container
      - ./db:/app/db
    # If you run behind a reverse-proxy (e.g. Traefik / Nginx) that adds
    # X-Forwarded-For, make sure to forward those headers so our middleware
    # can see the real client IP.
    networks:
      - geometa-net

networks:
  geometa-net:
    driver: bridge
