name = "geometa-gallery"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".next"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "geometa-dev"
database_id = "your-database-id-here"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB" 
database_name = "geometa-production"
database_id = "your-production-database-id-here"

# Development environment
[env.development]
vars = { NODE_ENV = "development" }

# Local development with wrangler dev
[[env.development.d1_databases]]
binding = "DB"
database_name = "geometa-dev"
database_id = "your-dev-database-id-here"