name = "geometa-gallery"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "geometa_gallery"
database_name = "geometa-gallery"
database_id = "08ad1d84-9ec7-4ca8-8ced-25995947d0c4"
